---
services:
  borildenstudio:
    image: nginx:1-alpine
    restart: unless-stopped

    volumes:
      - /mnt/HDDs/Applications/borilden-studio/astro-site/dist:/usr/share/nginx/html:ro

    networks:
      caddy_net:
        aliases:
          - borildenstudio
          - borilden-studio

networks:
  caddy_net:
    external: true
