---
services:
  borildenstudio:
    build:
      context: ./astro-site
    image: borilden-studio:latest
    container_name: borilden-studio
    restart: unless-stopped

    networks:
      - caddy_net

networks:
  caddy_net:
    external: true